2020-11-06 20:04:24,761 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:04:25,180 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:04:26,223 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:05:23,847 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:05:24,147 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:05:24,149 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:09:11,260 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:09:11,670 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:09:11,672 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:13:43,848 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:13:44,234 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:13:44,235 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:14:56,099 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:14:56,465 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:14:56,467 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:18:03,417 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:18:03,826 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:18:03,827 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 27, in netconf_get
    scrapli_conn = task.host.get_connection("scrapli_netconf", task.nornir.config)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/inventory.py", line 492, in open_connection
    conn_obj.open(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/connection.py", line 166, in open
    connection.open()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 64, in open
    login_bytes = self.transport.open_netconf()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 35, in open_netconf
    login_bytes = self._open_netconf_pty()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 55, in _open_netconf_pty
    login_bytes: bytes = self._authenticate()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/transport/systemssh.py", line 106, in _authenticate
    raise ScrapliAuthenticationFailed(msg)
scrapli.exceptions.ScrapliAuthenticationFailed: `password` seen multiple times during session establishment, likely failed authentication

2020-11-06 20:19:19,855 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="16843009"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 20:20:45,871 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:22:57,949 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:25:51,382 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:28:14,281 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:29:50,269 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:30:51,523 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:31:42,347 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:32:06,775 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:34:19,634 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:34:54,667 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:35:34,844 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:40:21,518 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:40:48,467 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:53:39,413 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:56:35,237 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 20:58:31,843 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:02:48,545 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:04:17,775 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:05:27,694 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:05:29,504 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 21:05:29,620 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="2.2.2.2"]/state'} on 2 hosts
2020-11-06 21:05:56,548 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:05:57,760 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]'} on 2 hosts
2020-11-06 21:05:57,987 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]'} on 2 hosts
2020-11-06 21:23:00,870 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:24:29,451 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:25:23,463 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:28:08,061 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:28:58,218 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:30:10,375 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:31:24,145 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:33:24,578 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:34:10,434 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:34:29,461 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:35:01,990 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:35:58,020 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:36:49,874 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:37:18,912 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:37:32,958 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:38:01,230 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:38:26,171 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:39:48,837 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:40:26,043 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:41:56,640 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:42:13,024 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:44:00,441 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:44:38,669 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:45:40,530 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:47:15,129 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:47:16,410 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.1]/state'} on 2 hosts
2020-11-06 21:47:16,534 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.2]/state'} on 2 hosts
2020-11-06 21:47:45,668 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:47:46,809 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.1]/state'} on 2 hosts
2020-11-06 21:47:46,904 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.2]/state'} on 2 hosts
2020-11-06 21:48:50,775 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:48:51,974 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0]/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.1]/state'} on 2 hosts
2020-11-06 21:48:52,044 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0]/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.2]/state'} on 2 hosts
2020-11-06 21:51:31,113 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:51:32,431 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0]/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.1]/state'} on 2 hosts
2020-11-06 21:51:32,535 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0]/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.2]/state'} on 2 hosts
2020-11-06 21:51:52,284 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:52:38,060 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:52:39,294 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0]/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.1]/state'} on 2 hosts
2020-11-06 21:52:39,387 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0]/ospf-interface[name=GigabitEthernet2]/ospf-neighbor[neighbor-id=172.16.16.2]/state'} on 2 hosts
2020-11-06 21:53:44,223 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:53:45,537 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="172.16.16.1""]/state'} on 2 hosts
2020-11-06 21:53:45,606 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="172.16.16.2""]/state'} on 2 hosts
2020-11-06 21:54:03,753 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance'} on 2 hosts
2020-11-06 21:54:04,893 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733826"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="172.16.16.1"]/state'} on 2 hosts
2020-11-06 21:54:05,000 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '/ospf-oper-data/ospf-state/ospf-instance[af="address-family-ipv4" and router-id="2886733825"]/ospf-area[area-id=0]/ospf-interface[name="GigabitEthernet2"]/ospf-neighbor[neighbor-id="172.16.16.2"]/state'} on 2 hosts
2020-11-07 19:48:52,727 -  nornir.core -     INFO -        run() - Running task 'netconf_get' with args {'filter_type': 'xpath', 'filter_': '//ospf-neighbor/state'} on 2 hosts
2020-11-07 20:00:09,868 -  nornir.core -     INFO -        run() - Running task 'ospf_nbr_state' with args {} on 2 hosts
2020-11-07 20:03:05,753 -  nornir.core -     INFO -        run() - Running task 'ospf_nbr_state' with args {} on 2 hosts
2020-11-07 20:03:18,650 -  nornir.core -     INFO -        run() - Running task 'ospf_nbr_state' with args {} on 2 hosts
2020-11-07 20:04:13,472 -  nornir.core -     INFO -        run() - Running task 'ospf_nbr_state' with args {} on 2 hosts
2020-11-07 20:04:51,202 -  nornir.core -     INFO -        run() - Running task 'ospf_nbr_state' with args {} on 2 hosts
2020-11-07 20:32:43,918 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:32:43,922 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'netconf_get_config' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: netconf_get_config() got an unexpected keyword argument 'filter_'

2020-11-07 20:32:43,922 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get_config' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
TypeError: netconf_get_config() got an unexpected keyword argument 'filter_'

2020-11-07 20:32:43,923 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 15, in check_for_isis
    result = task.run(task=netconf_get_config, filter_type='xpath',
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_get_config (failed)


2020-11-07 20:32:43,923 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 15, in check_for_isis
    result = task.run(task=netconf_get_config, filter_type='xpath',
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_get_config (failed)


2020-11-07 20:36:59,221 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:41:48,674 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:41:51,141 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 17, in check_for_isis
    isis_state = data['data']['router']['isis']
KeyError: 'data'

2020-11-07 20:41:51,293 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 17, in check_for_isis
    isis_state = data['data']['router']['isis']
KeyError: 'data'

2020-11-07 20:42:15,975 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:42:17,868 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 18, in check_for_isis
    isis_state = data['data']['router']['isis']
KeyError: 'data'

2020-11-07 20:42:18,367 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 18, in check_for_isis
    isis_state = data['data']['router']['isis']
KeyError: 'data'

2020-11-07 20:42:53,432 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:42:55,477 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 18, in check_for_isis
    isis_state = data['rpc-reply']['data']['router']['isis']
KeyError: 'router'

2020-11-07 20:42:55,535 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 18, in check_for_isis
    isis_state = data['rpc-reply']['data']['router']['isis']
KeyError: 'router'

2020-11-07 20:43:56,415 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:43:58,855 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 19, in check_for_isis
    isis_state = data['rpc-reply']['data']['router']['isis']
KeyError: 'router'

2020-11-07 20:43:59,197 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 19, in check_for_isis
    isis_state = data['rpc-reply']['data']['router']['isis']
KeyError: 'router'

2020-11-07 20:45:17,349 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:45:19,681 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 19, in check_for_isis
    isis_state = data['rpc-reply']['data']['router']['isis']
KeyError: 'router'

2020-11-07 20:45:19,805 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 19, in check_for_isis
    isis_state = data['rpc-reply']['data']['router']['isis']
KeyError: 'router'

2020-11-07 20:45:39,930 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:45:42,167 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 19, in check_for_isis
    isis_state = data['rpc-reply']['data']['native']['router']['isis']
KeyError: 'isis'

2020-11-07 20:46:52,164 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:46:54,156 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 20, in check_for_isis
    isis_state = data['rpc-reply']['data']['native']['router']['isis']
KeyError: 'isis'

2020-11-07 20:47:44,031 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:47:46,238 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 20, in check_for_isis
    isis_state = data['rpc-reply']['data']['native']['router']['isis']
KeyError: 'isis'

2020-11-07 20:48:34,637 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:48:36,594 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 21, in check_for_isis
    if data['rpc-reply']['data']['native']['router']['isis']:
KeyError: 'isis'

2020-11-07 20:49:36,438 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:49:38,585 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 21, in check_for_isis
    if data['rpc-reply']['data']['native']['router']['isis']:
KeyError: 'isis'

2020-11-07 20:50:00,512 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 20:50:02,607 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 21, in check_for_isis
    if 'isis' in data['rpc-reply']['data']['native']['router']['isis']:
KeyError: 'isis'

2020-11-07 20:50:15,923 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:00:05,499 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:00:18,178 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 767, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 28, in netconf_get
    scrapli_response = scrapli_conn.get(filter_=filter_, filter_type=filter_type)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 97, in get
    raw_response = self.channel.send_input_netconf(response.channel_input)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/channel/channel.py", line 216, in send_input_netconf
    raw_result = self._read_until_prompt(output=raw_result)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/channel/channel.py", line 121, in _read_until_prompt
    output += self._read_chunk()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/channel/channel.py", line 49, in _read_chunk
    new_output = self.transport.read()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 313, in requires_open_session_wrapper
    return wrapped_func(*args, **kwargs)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 288, in multiprocessing_timeout
    self._handle_timeout()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 192, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: Timed out reading from transport

2020-11-07 21:00:18,179 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 27, in check_for_isis
    bia_results = task.run(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_get (failed)


2020-11-07 21:00:57,554 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:01:11,145 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'netconf_get' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 767, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/.local/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_get.py", line 28, in netconf_get
    scrapli_response = scrapli_conn.get(filter_=filter_, filter_type=filter_type)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/driver/driver.py", line 97, in get
    raw_response = self.channel.send_input_netconf(response.channel_input)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli_netconf/channel/channel.py", line 216, in send_input_netconf
    raw_result = self._read_until_prompt(output=raw_result)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/channel/channel.py", line 121, in _read_until_prompt
    output += self._read_chunk()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/channel/channel.py", line 49, in _read_chunk
    new_output = self.transport.read()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 313, in requires_open_session_wrapper
    return wrapped_func(*args, **kwargs)
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 113, in decorate
    return self.multiprocessing_timeout(
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 288, in multiprocessing_timeout
    self._handle_timeout()
  File "/home/knox/.local/lib/python3.8/site-packages/scrapli/decorators.py", line 192, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: Timed out reading from transport

2020-11-07 21:01:11,147 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 27, in check_for_isis
    bia_results = task.run(
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_get (failed)


2020-11-07 21:02:49,462 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:02:54,556 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 35, in check_for_isis
    <net>49.0000.{BIA}.00</net>
NameError: name 'BIA' is not defined

2020-11-07 21:09:06,461 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:09:11,483 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 30, in check_for_isis
    bia = mac_dict['rpc-reply']['interfaces']['interface']['bia-address']
KeyError: 'interfaces'

2020-11-07 21:09:53,607 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:09:58,184 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 36, in check_for_isis
    <net>49.0000.{BIA}.00</net>
NameError: name 'BIA' is not defined

2020-11-07 21:12:16,863 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:12:21,729 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 42, in check_for_isis
    task.run(task=netconf_edit_config,
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-11-07 21:13:47,227 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:13:52,217 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 44, in check_for_isis
    task.run(task=netconf_edit_config,
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-11-07 21:15:40,897 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:15:45,709 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 44, in check_for_isis
    task.run(task=netconf_edit_config,
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-11-07 21:16:34,459 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:16:38,949 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 44, in check_for_isis
    task.run(task=netconf_edit_config,
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-11-07 21:17:22,745 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:17:28,439 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 46, in check_for_isis
    task.run(task=netconf_edit_config,
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 168, in run
    raise NornirSubTaskError(task=run_task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: netconf_edit_config (failed)


2020-11-07 21:24:04,356 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:24:08,927 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'check_for_isis' failed with traceback:
Traceback (most recent call last):
  File "/home/knox/.local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 33, in check_for_isis
    bia = '-'.join(a+b+c+d for a, b, c, d in zip(t, t))
  File "/home/knox/Documents/CodeSamples/Python/Networking/Nornir/scraplisis.py", line 33, in <genexpr>
    bia = '-'.join(a+b+c+d for a, b, c, d in zip(t, t))
ValueError: not enough values to unpack (expected 4, got 2)

2020-11-07 21:25:31,533 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:31:40,456 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 21:36:49,570 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 22:09:46,893 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
2020-11-07 22:11:24,702 -  nornir.core -     INFO -        run() - Running task 'check_for_isis' with args {} on 2 hosts
