2020-10-23 09:59:53,337 INFO myApi MainThread : script directory: C:\Code\CodeSamples\Python\AppDev
2020-10-23 09:59:53,338 INFO myApi MainThread : DB file: C:\Code\CodeSamples\Python\AppDev\db.txt
2020-10-23 09:59:53,352 INFO werkzeug MainThread :  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-10-23 10:00:01,224 INFO werkzeug Thread-7 : 127.0.0.1 - - [23/Oct/2020 10:00:01] "[37mGET / HTTP/1.1[0m" 200 -
2020-10-23 10:00:26,878 WARNING myApi Thread-8 : No hostname specified
2020-10-23 10:00:26,879 ERROR myApi Thread-8 : NO HOSTNAME SPECIFIED
2020-10-23 10:00:26,880 INFO werkzeug Thread-8 : 127.0.0.1 - - [23/Oct/2020 10:00:26] "[31m[1mGET /routers HTTP/1.1[0m" 400 -
2020-10-23 10:00:38,353 WARNING myApi Thread-9 : No hostname specified
2020-10-23 10:00:38,353 ERROR myApi Thread-9 : NO HOSTNAME SPECIFIED
2020-10-23 10:00:38,354 INFO werkzeug Thread-9 : 127.0.0.1 - - [23/Oct/2020 10:00:38] "[31m[1mGET /routers?hostname= HTTP/1.1[0m" 400 -
2020-10-23 10:00:51,293 WARNING myApi Thread-10 : No matching router
2020-10-23 10:00:51,294 INFO werkzeug Thread-10 : 127.0.0.1 - - [23/Oct/2020 10:00:51] "[37mGET /routers?hostname=R1 HTTP/1.1[0m" 200 -
2020-10-23 10:01:02,404 INFO myApi Thread-11 : Routers returned
2020-10-23 10:01:02,405 INFO werkzeug Thread-11 : 127.0.0.1 - - [23/Oct/2020 10:01:02] "[37mGET /routers?hostname=SW1 HTTP/1.1[0m" 200 -
2020-10-23 10:05:11,470 INFO myApi MainThread : script directory: C:\Code\CodeSamples\Python\AppDev
2020-10-23 10:05:11,471 INFO myApi MainThread : DB file: C:\Code\CodeSamples\Python\AppDev\db.txt
2020-10-23 10:05:11,484 INFO werkzeug MainThread :  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-10-23 10:06:51,307 INFO myApi Thread-7 : inbound record {'hostname': 'R1', 'ipadd': '10.0.0.1'}
2020-10-23 10:06:51,308 INFO myApi Thread-7 : records output [{'hostname': 'SW1', 'ipaddr': '10.12.12.1'}, {'hostname': 'R1', 'ipadd': '10.0.0.1'}]
2020-10-23 10:06:51,308 WARNING myApi Thread-7 : router added R1
2020-10-23 10:06:51,311 INFO werkzeug Thread-7 : 127.0.0.1 - - [23/Oct/2020 10:06:51] "[37mPOST /routers HTTP/1.1[0m" 201 -
2020-10-23 10:07:08,592 INFO myApi Thread-8 : inbound record {'hostname': 'R1', 'ipadd': '10.0.0.1'}
2020-10-23 10:07:08,598 INFO werkzeug Thread-8 : 127.0.0.1 - - [23/Oct/2020 10:07:08] "[37mPOST /routers HTTP/1.1[0m" 200 -
2020-10-23 10:07:38,834 INFO myApi Thread-9 : inbound record {'hostame': 'R1', 'ipadd': '10.0.0.1'}
2020-10-23 10:07:38,835 INFO myApi Thread-9 : records output [{'hostname': 'SW1', 'ipaddr': '10.12.12.1'}, {'hostname': 'R1', 'ipadd': '10.0.0.1'}, {'hostame': 'R1', 'ipadd': '10.0.0.1'}]
2020-10-23 10:07:38,835 ERROR myApi Thread-9 : Error during ADD 'hostname'
2020-10-23 10:07:38,836 ERROR myApi Thread-9 : Exception on /routers [POST]
Traceback (most recent call last):
  File "c:\Code\CodeSamples\Python\AppDev\myApi.py", line 71, in addRouter
    LOG.warning(f'router added {record["hostname"]}')
KeyError: 'hostname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Code\CodeSamples\Python\AppDev\myApi.py", line 77, in addRouter
    return jsonify({"error": err})
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2020-10-23 10:07:38,848 INFO werkzeug Thread-9 : 127.0.0.1 - - [23/Oct/2020 10:07:38] "[35m[1mPOST /routers HTTP/1.1[0m" 500 -
2020-10-23 10:14:18,114 INFO myApi MainThread : script directory: C:\Code\CodeSamples\Python\AppDev
2020-10-23 10:14:18,115 INFO myApi MainThread : DB file: C:\Code\CodeSamples\Python\AppDev\db.txt
2020-10-23 10:14:18,129 INFO werkzeug MainThread :  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-10-23 10:14:49,291 WARNING myApi Thread-7 : Deleted R1
2020-10-23 10:14:49,293 INFO werkzeug Thread-7 : 127.0.0.1 - - [23/Oct/2020 10:14:49] "[37mDELETE /routers HTTP/1.1[0m" 204 -
2020-10-23 10:15:20,524 INFO werkzeug Thread-8 : 127.0.0.1 - - [23/Oct/2020 10:15:20] "[37mDELETE /routers HTTP/1.1[0m" 204 -
2020-10-23 10:15:34,703 ERROR myApi Thread-9 : ERROR RAISED: 'hostname'
2020-10-23 10:15:34,704 ERROR myApi Thread-9 : Exception on /routers [DELETE]
Traceback (most recent call last):
  File "c:\Code\CodeSamples\Python\AppDev\myApi.py", line 91, in deleteRouter
    if r['hostname'] == record['hostname']:
KeyError: 'hostname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Code\CodeSamples\Python\AppDev\myApi.py", line 100, in deleteRouter
    return jsonify({"error": err})
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Python\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KeyError is not JSON serializable
2020-10-23 10:15:34,715 INFO werkzeug Thread-9 : 127.0.0.1 - - [23/Oct/2020 10:15:34] "[35m[1mDELETE /routers HTTP/1.1[0m" 500 -
2020-10-23 10:15:46,059 INFO werkzeug Thread-10 : 127.0.0.1 - - [23/Oct/2020 10:15:46] "[33mDELETE /router HTTP/1.1[0m" 404 -
